spec:
  template:
    spec:
      volumes:
        - name: app-pvc
          persistentVolumeClaim:
            claimName: kogito-app-pvc2
      containers:
        - name: kogito-management-console
          volumeMounts:
            - name: app-pvc
              mountPath: /home/kogito/data/svg
          env:
            - name: KOGITO_DATAINDEX_HTTP_URL
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: kogito.dataindex.httpurl.with.graphql
            - name: KOGITO_MANAGEMENT_CONSOLE_PROPS
              valueFrom:
                configMapKeyRef:
                  name: kogito-configs
                  key: kogito.managementconsole.props