apiVersion: v1
kind: ConfigMap
metadata:
  name: kogito-configs
data:
    quarkus.infinispan.client.authusername: 'developer'
    quarkus.infinispan.client.serverlist: 'infinispan.${project_name}.svc.cluster.local:11222'
    kafka.bootstrap.servers: 'kafka.${project_name}.svc.cluster.local:9092'
    kogito.dataindex.props: '-Dkogito.protobuf.folder=/home/kogito/data/protobufs/'
    kogito.dataindex.httpurl: 'http://kogito-data-index-infinispan-${project_name}.${apps_cluster_host}'
    kogito.dataindex.wsurl: 'ws://kogito-data-index-infinispan-${project_name}.${apps_cluster_host}'
    kogito.managementconsole.props: '-Dkogito.svg.folder.path=/home/kogito/data/svg -Dquarkus.oidc.auth-server-url=none -Dquarkus.oidc.tenant-enabled=false'